# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'civilization_design_file.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

import os

art_dir = os.path.join( os.path.dirname(__file__), '..', '..', 'Artwork' )

class editor_gui_window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1004, 834)
        MainWindow.setMinimumSize(QtCore.QSize(800, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.ent_select_button_0 = QtWidgets.QToolButton(self.centralwidget)
        self.ent_select_button_0.setMinimumSize(QtCore.QSize(40, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join( art_dir, "select_location.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ent_select_button_0.setIcon(icon)
        self.ent_select_button_0.setIconSize(QtCore.QSize(32, 32))
        self.ent_select_button_0.setObjectName("ent_select_button_0")
        self.verticalLayout.addWidget(self.ent_select_button_0)
        self.count_sel_button_1 = QtWidgets.QToolButton(self.centralwidget)
        self.count_sel_button_1.setMinimumSize(QtCore.QSize(40, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(art_dir, "temp.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.count_sel_button_1.setIcon(icon1)
        self.count_sel_button_1.setIconSize(QtCore.QSize(32, 32))
        self.count_sel_button_1.setObjectName("count_sel_button_1")
        self.verticalLayout.addWidget(self.count_sel_button_1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.loc_button_1 = QtWidgets.QToolButton(self.centralwidget)
        self.loc_button_1.setMinimumSize(QtCore.QSize(40, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(art_dir, "new_location.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loc_button_1.setIcon(icon2)
        self.loc_button_1.setIconSize(QtCore.QSize(32, 32))
        self.loc_button_1.setObjectName("loc_button_1")
        self.verticalLayout.addWidget(self.loc_button_1)
        self.setl_button_2 = QtWidgets.QToolButton(self.centralwidget)
        self.setl_button_2.setMinimumSize(QtCore.QSize(40, 40))
        self.setl_button_2.setIcon(icon1)
        self.setl_button_2.setIconSize(QtCore.QSize(32, 32))
        self.setl_button_2.setObjectName("setl_button_2")
        self.verticalLayout.addWidget(self.setl_button_2)
        self.road_button_3 = QtWidgets.QToolButton(self.centralwidget)
        self.road_button_3.setMinimumSize(QtCore.QSize(40, 40))
        self.road_button_3.setIcon(icon1)
        self.road_button_3.setIconSize(QtCore.QSize(32, 32))
        self.road_button_3.setObjectName("road_button_3")
        self.verticalLayout.addWidget(self.road_button_3)
        self.count_button_4 = QtWidgets.QToolButton(self.centralwidget)
        self.count_button_4.setMinimumSize(QtCore.QSize(40, 40))
        self.count_button_4.setIcon(icon1)
        self.count_button_4.setIconSize(QtCore.QSize(32, 32))
        self.count_button_4.setObjectName("count_button_4")
        self.verticalLayout.addWidget(self.count_button_4)
        self.kingdom_button_5 = QtWidgets.QToolButton(self.centralwidget)
        self.kingdom_button_5.setMinimumSize(QtCore.QSize(40, 40))
        self.kingdom_button_5.setIcon(icon1)
        self.kingdom_button_5.setIconSize(QtCore.QSize(32, 32))
        self.kingdom_button_5.setObjectName("kingdom_button_5")
        self.verticalLayout.addWidget(self.kingdom_button_5)
        self.hand_button_6 = QtWidgets.QToolButton(self.centralwidget)
        self.hand_button_6.setMinimumSize(QtCore.QSize(40, 40))
        self.hand_button_6.setIcon(icon1)
        self.hand_button_6.setIconSize(QtCore.QSize(32, 32))
        self.hand_button_6.setObjectName("hand_button_6")
        self.verticalLayout.addWidget(self.hand_button_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setMinimumSize(QtCore.QSize(250, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.Locations = QtWidgets.QWidget()
        self.Locations.setGeometry(QtCore.QRect(0, 0, 250, 617))
        self.Locations.setObjectName("Locations")
        self.formLayoutWidget = QtWidgets.QWidget(self.Locations)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 0, 231, 591))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.loc_name_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.loc_name_label.setObjectName("loc_name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.loc_name_label)
        self.loc_name_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.loc_name_edit.setObjectName("loc_name_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loc_name_edit)
        self.loc_desc_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.loc_desc_label.setObjectName("loc_desc_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.loc_desc_label)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.loc_desc_edit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.loc_desc_edit.setObjectName("loc_desc_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.loc_desc_edit)
        self.loc_save = QtWidgets.QPushButton(self.formLayoutWidget)
        self.loc_save.setObjectName("loc_save")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.loc_save)
        self.status_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.status_label.setMinimumSize(QtCore.QSize(80, 0))
        self.status_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.status_label.setFrameShape(QtWidgets.QFrame.Box)
        self.status_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.status_label)
        self.loc_list_view = QtWidgets.QListView(self.formLayoutWidget)
        self.loc_list_view.setObjectName("loc_list_view")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.loc_list_view)
        self.loc_list_entry = QtGui.QStandardItemModel()
        self.loc_list_view.setModel( self.loc_list_entry )

        self.loc_delete = QtWidgets.QPushButton(self.formLayoutWidget)
        self.loc_delete.setObjectName("loc_delete")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.loc_delete)
        self.loc_deselect = QtWidgets.QPushButton(self.formLayoutWidget)
        self.loc_deselect.setObjectName("loc_deselect")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.loc_deselect)
        self.toolBox.addItem(self.Locations, "")
        self.settlement = QtWidgets.QWidget()
        self.settlement.setGeometry(QtCore.QRect(0, 0, 250, 597))
        self.settlement.setObjectName("settlement")
        self.toolBox.addItem(self.settlement, "")
        self.Roads = QtWidgets.QWidget()
        self.Roads.setGeometry(QtCore.QRect(0, 0, 250, 597))
        self.Roads.setObjectName("Roads")
        self.toolBox.addItem(self.Roads, "")
        self.Counties = QtWidgets.QWidget()
        self.Counties.setGeometry(QtCore.QRect(0, 0, 250, 597))
        self.Counties.setObjectName("Counties")
        self.toolBox.addItem(self.Counties, "")
        self.Kingdoms = QtWidgets.QWidget()
        self.Kingdoms.setGeometry(QtCore.QRect(0, 0, 250, 597))
        self.Kingdoms.setObjectName("Kingdoms")
        self.toolBox.addItem(self.Kingdoms, "")
        self.horizontalLayout.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1004, 22))
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBiome_Borders = QtWidgets.QAction(MainWindow)
        self.actionBiome_Borders.setCheckable(True)
        self.actionBiome_Borders.setObjectName("actionBiome_Borders")
        self.actionCounty_Borders = QtWidgets.QAction(MainWindow)
        self.actionCounty_Borders.setCheckable(True)
        self.actionCounty_Borders.setChecked(True)
        self.actionCounty_Borders.setObjectName("actionCounty_Borders")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionAbout_MultiHex = QtWidgets.QAction(MainWindow)
        self.actionAbout_MultiHex.setObjectName("actionAbout_MultiHex")
        self.actionBiome_Names = QtWidgets.QAction(MainWindow)
        self.actionBiome_Names.setCheckable(True)
        self.actionBiome_Names.setChecked(True)
        self.actionBiome_Names.setObjectName("actionBiome_Names")
        self.actionCounty_Names = QtWidgets.QAction(MainWindow)
        self.actionCounty_Names.setCheckable(True)
        self.actionCounty_Names.setChecked(True)
        self.actionCounty_Names.setObjectName("actionCounty_Names")
        self.actionTowns = QtWidgets.QAction(MainWindow)
        self.actionTowns.setCheckable(True)
        self.actionTowns.setChecked(True)
        self.actionTowns.setObjectName("actionTowns")
        self.actionLocations = QtWidgets.QAction(MainWindow)
        self.actionLocations.setCheckable(True)
        self.actionLocations.setChecked(True)
        self.actionLocations.setObjectName("actionLocations")
        self.menuView.addAction(self.actionBiome_Borders)
        self.menuView.addAction(self.actionBiome_Names)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionLocations)
        self.menuView.addAction(self.actionTowns)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionCounty_Borders)
        self.menuView.addAction(self.actionCounty_Names)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout_MultiHex)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ent_select_button_0.setText(_translate("MainWindow", "..."))
        self.count_sel_button_1.setText(_translate("MainWindow", "..."))
        self.loc_button_1.setText(_translate("MainWindow", "..."))
        self.setl_button_2.setText(_translate("MainWindow", "..."))
        self.road_button_3.setText(_translate("MainWindow", "..."))
        self.count_button_4.setText(_translate("MainWindow", "..."))
        self.kingdom_button_5.setText(_translate("MainWindow", "..."))
        self.hand_button_6.setText(_translate("MainWindow", "..."))
        self.loc_name_label.setText(_translate("MainWindow", "Name"))
        self.loc_desc_label.setText(_translate("MainWindow", "\n"
" Description"))
        self.loc_save.setText(_translate("MainWindow", "Save"))
        self.status_label.setText(_translate("MainWindow", "..."))
        self.loc_delete.setText(_translate("MainWindow", "Delete"))
        self.loc_deselect.setText(_translate("MainWindow", "Deselect"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Locations), _translate("MainWindow", "Locations"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.settlement), _translate("MainWindow", "Settlement"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Roads), _translate("MainWindow", "Roads"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Counties), _translate("MainWindow", "Counties"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Kingdoms), _translate("MainWindow", "Kingoms"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionBiome_Borders.setText(_translate("MainWindow", "Biome Borders"))
        self.actionCounty_Borders.setText(_translate("MainWindow", "County Borders"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionAbout_MultiHex.setText(_translate("MainWindow", "About MultiHex"))
        self.actionBiome_Names.setText(_translate("MainWindow", "Biome Names"))
        self.actionCounty_Names.setText(_translate("MainWindow", "County Names"))
        self.actionTowns.setText(_translate("MainWindow", "Towns"))
        self.actionLocations.setText(_translate("MainWindow", "Locations"))

#import resource_file_rc
