# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class editor_gui_window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(926, 699)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Forest = QtWidgets.QPushButton(self.centralwidget)
        self.Forest.setObjectName("Forest")
        self.horizontalLayout.addWidget(self.Forest)
        self.Grassland = QtWidgets.QPushButton(self.centralwidget)
        self.Grassland.setObjectName("Grassland")
        self.horizontalLayout.addWidget(self.Grassland)
        self.Ocean = QtWidgets.QPushButton(self.centralwidget)
        self.Ocean.setObjectName("Ocean")
        self.horizontalLayout.addWidget(self.Ocean)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.Ridge = QtWidgets.QPushButton(self.centralwidget)
        self.Ridge.setObjectName("Ridge")
        self.horizontalLayout.addWidget(self.Ridge)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hexBrush = QtWidgets.QRadioButton(self.centralwidget)
        self.hexBrush.setObjectName("hexBrush")
        self.verticalLayout_2.addWidget(self.hexBrush)
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.brushToggle = QtWidgets.QCheckBox(self.centralwidget)
        self.brushToggle.setObjectName("brushToggle")
        self.verticalLayout_2.addWidget(self.brushToggle)
        self.brushSize = QtWidgets.QSpinBox(self.centralwidget)
        self.brushSize.setMinimum(1)
        self.brushSize.setMaximum(2)
        self.brushSize.setObjectName("brushSize")
        self.verticalLayout_2.addWidget(self.brushSize)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.biodiversity = QtWidgets.QSlider(self.centralwidget)
        self.biodiversity.setOrientation(QtCore.Qt.Vertical)
        self.biodiversity.setObjectName("biodiversity")
        self.horizontalLayout_2.addWidget(self.biodiversity)
        self.temperature = QtWidgets.QSlider(self.centralwidget)
        self.temperature.setOrientation(QtCore.Qt.Vertical)
        self.temperature.setObjectName("temperature")
        self.horizontalLayout_2.addWidget(self.temperature)
        self.rainfall = QtWidgets.QSlider(self.centralwidget)
        self.rainfall.setOrientation(QtCore.Qt.Vertical)
        self.rainfall.setObjectName("rainfall")
        self.horizontalLayout_2.addWidget(self.rainfall)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RegLab = QtWidgets.QLabel(self.centralwidget)
        self.RegLab.setObjectName("RegLab")
        self.horizontalLayout_3.addWidget(self.RegLab)
        self.RegEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RegEdit.setObjectName("RegEdit")
        self.horizontalLayout_3.addWidget(self.RegEdit)
        self.RegButton = QtWidgets.QPushButton(self.centralwidget)
        self.RegButton.setObjectName("RegButton")
        self.horizontalLayout_3.addWidget(self.RegButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 926, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Forest.setText(_translate("MainWindow", "Forest"))
        self.Grassland.setText(_translate("MainWindow", "Grassland"))
        self.Ocean.setText(_translate("MainWindow", "Ocean"))
        self.pushButton_8.setText(_translate("MainWindow", "Arctic"))
        self.pushButton_7.setText(_translate("MainWindow", "Desert"))
        self.pushButton_9.setText(_translate("MainWindow", "Mountains"))
        self.Ridge.setText(_translate("MainWindow", "Ridgeline"))
        self.hexBrush.setText(_translate("MainWindow", "Hex Brush"))
        self.radioButton.setText(_translate("MainWindow", "Region Brush"))
        self.brushToggle.setText(_translate("MainWindow", "Drawing"))
        self.label.setText(_translate("MainWindow", "Bio  Temp  Rain"))
        self.pushButton_4.setText(_translate("MainWindow", "Save"))
        self.pushButton_6.setText(_translate("MainWindow", "Save as..."))
        self.pushButton_5.setText(_translate("MainWindow", "Quit"))
        self.label_2.setText(_translate("MainWindow", "Status OK"))
        self.RegLab.setText(_translate("MainWindow", "Region Name:"))
        self.RegButton.setText(_translate("MainWindow", "Set"))

