# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ward_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(608, 418)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(Dialog)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.name_edit = QtWidgets.QLineEdit(Dialog)
        self.name_edit.setObjectName("name_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name_edit)
        self.walled_chck = QtWidgets.QCheckBox(Dialog)
        self.walled_chck.setObjectName("walled_chck")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.walled_chck)
        self.pop_wea_grid = QtWidgets.QGridLayout()
        self.pop_wea_grid.setObjectName("pop_wea_grid")
        self.pop_value = QtWidgets.QLabel(Dialog)
        self.pop_value.setMinimumSize(QtCore.QSize(150, 0))
        self.pop_value.setFrameShape(QtWidgets.QFrame.Box)
        self.pop_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pop_value.setText("")
        self.pop_value.setObjectName("pop_value")
        self.pop_wea_grid.addWidget(self.pop_value, 0, 1, 1, 1)
        self.pop_dropdown = QtWidgets.QComboBox(Dialog)
        self.pop_dropdown.setObjectName("pop_dropdown")
        self.pop_dropdown.addItem("")
        self.pop_dropdown.addItem("")
        self.pop_dropdown.addItem("")
        self.pop_wea_grid.addWidget(self.pop_dropdown, 0, 2, 1, 1)
        self.pop_lbl = QtWidgets.QLabel(Dialog)
        self.pop_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pop_lbl.setObjectName("pop_lbl")
        self.pop_wea_grid.addWidget(self.pop_lbl, 0, 0, 1, 1)
        self.pop_edit = QtWidgets.QLineEdit(Dialog)
        self.pop_edit.setObjectName("pop_edit")
        self.pop_wea_grid.addWidget(self.pop_edit, 0, 3, 1, 1)
        self.wealth_lbl = QtWidgets.QLabel(Dialog)
        self.wealth_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wealth_lbl.setObjectName("wealth_lbl")
        self.pop_wea_grid.addWidget(self.wealth_lbl, 1, 0, 1, 1)
        self.wealth_value = QtWidgets.QLabel(Dialog)
        self.wealth_value.setFrameShape(QtWidgets.QFrame.Box)
        self.wealth_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wealth_value.setText("")
        self.wealth_value.setObjectName("wealth_value")
        self.pop_wea_grid.addWidget(self.wealth_value, 1, 1, 1, 1)
        self.wealth_dropdown = QtWidgets.QComboBox(Dialog)
        self.wealth_dropdown.setObjectName("wealth_dropdown")
        self.wealth_dropdown.addItem("")
        self.wealth_dropdown.addItem("")
        self.wealth_dropdown.addItem("")
        self.pop_wea_grid.addWidget(self.wealth_dropdown, 1, 2, 1, 1)
        self.wealth_edit = QtWidgets.QLineEdit(Dialog)
        self.wealth_edit.setObjectName("wealth_edit")
        self.pop_wea_grid.addWidget(self.wealth_edit, 1, 3, 1, 1)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.pop_wea_grid)
        self.order_lbl = QtWidgets.QLabel(Dialog)
        self.order_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.order_lbl.setObjectName("order_lbl")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.order_lbl)
        self.order_slider = QtWidgets.QSlider(Dialog)
        self.order_slider.setOrientation(QtCore.Qt.Horizontal)
        self.order_slider.setObjectName("order_slider")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.order_slider)
        self.war_lbl = QtWidgets.QLabel(Dialog)
        self.war_lbl.setObjectName("war_lbl")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.war_lbl)
        self.war_slider = QtWidgets.QSlider(Dialog)
        self.war_slider.setOrientation(QtCore.Qt.Horizontal)
        self.war_slider.setObjectName("war_slider")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.war_slider)
        self.spirit_lbl = QtWidgets.QLabel(Dialog)
        self.spirit_lbl.setObjectName("spirit_lbl")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.spirit_lbl)
        self.spirit_slider = QtWidgets.QSlider(Dialog)
        self.spirit_slider.setOrientation(QtCore.Qt.Horizontal)
        self.spirit_slider.setObjectName("spirit_slider")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spirit_slider)
        self.demo_dd_label = QtWidgets.QLabel(Dialog)
        self.demo_dd_label.setObjectName("demo_dd_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.demo_dd_label)
        self.accept_reject = QtWidgets.QDialogButtonBox(Dialog)
        self.accept_reject.setOrientation(QtCore.Qt.Horizontal)
        self.accept_reject.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.accept_reject.setObjectName("accept_reject")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.accept_reject)
        self.demo_edit = QtWidgets.QPlainTextEdit(Dialog)
        self.demo_edit.setObjectName("demo_edit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.demo_edit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
     #   self.checkBox = QtWidgets.QCheckBox(Dialog)
     #   self.checkBox.setChecked(True)
     #   self.checkBox.setObjectName("checkBox")
     #   self.horizontalLayout.addWidget(self.checkBox)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.accept_reject.accepted.connect(Dialog.accept)
        self.accept_reject.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.name_label.setText(_translate("Dialog", "Ward Name:"))
        self.walled_chck.setText(_translate("Dialog", "Is Walled"))
        self.pop_dropdown.setItemText(0, _translate("Dialog", "Keep At"))
        self.pop_dropdown.setItemText(1, _translate("Dialog", "Set To"))
        self.pop_dropdown.setItemText(2, _translate("Dialog", "Add"))
        self.pop_lbl.setText(_translate("Dialog", "Current Pop:"))
        self.wealth_lbl.setText(_translate("Dialog", "Current Wealth:"))
        self.wealth_dropdown.setItemText(0, _translate("Dialog", "Keep At"))
        self.wealth_dropdown.setItemText(1, _translate("Dialog", "Set To"))
        self.wealth_dropdown.setItemText(2, _translate("Dialog", "Add"))
        self.order_lbl.setText(_translate("Dialog", "Order: "))
        self.war_lbl.setText(_translate("Dialog", "War: "))
        self.spirit_lbl.setText(_translate("Dialog", "Spirit: "))
        self.demo_dd_label.setText(_translate("Dialog", "Demographic:"))
        self.demo_edit.setPlainText(_translate("Dialog", "# represents population to be added, or the set population"))
        self.comboBox.setItemText(0, _translate("Dialog", "Set Demographics To"))
        self.comboBox.addItem("Add to Demographics")
    #    self.checkBox.setText(_translate("Dialog", "Added? (else Set To)"))

